Repository thenolja/desktop, pull requests merged in 2022-04, with the labels that each got.

#187 리뷰 삭제 기능 구현
  backend/server.js
  frontend/src/components/Payment/Notice.tsx
  frontend/src/components/Payment/Payment.style.ts
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/Review.type.ts
  frontend/src/components/Review/ReviewList.tsx
  frontend/src/pages/Detail/Reviews.tsx
  frontend/src/pages/Reservation/Reservation.style.ts
  frontend/src/pages/Reviews/Reviews.tsx
  frontend/src/utils/reviews.ts
  frontend/src/utils/users.ts
Labels: feat

#190 리뷰 업로드시 호텔 리뷰 반영 및 예약 목데이터 정리
  backend/data/reservations.json
  frontend/src/components/Reservation/PostingReview.tsx
  frontend/src/utils/requests.ts
  frontend/src/utils/reviews.ts
Labels: bug

#203 main, search 컴포넌트 리펙토링
  frontend/src/app/app.tsx
  frontend/src/components/Carousels/CarouselLi/CarouselLi.tsx
  frontend/src/components/Carousels/MoveCarousel.tsx
  frontend/src/components/CheckInOut/Calendar.tsx
  frontend/src/components/Index/CurrentGoods/CurrentGoods.tsx
  frontend/src/components/Index/LocalGoods/LocalGoods.tsx
  frontend/src/components/Index/SearchForm/Input/EndDatPicker.tsx
  frontend/src/components/Index/SearchForm/Input/PersoInput.tsx
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/index.tsx
  frontend/src/pages/Detail/HotelIntro.tsx
  frontend/src/pages/Search/Search.tsx
  frontend/src/pages/Search/Search.type.ts
Labels: refactoring

#204 객실 컴포넌트화, 객실 타입 수정 및 예외 처리
  frontend/src/components/Room/DetailRoomInfo.tsx
  frontend/src/components/Room/Modal/DetailRoomInfo.tsx
  frontend/src/components/Room/Modal/Modal.style.ts
  frontend/src/components/Room/Modal/Modal.type.ts
  frontend/src/components/Room/Modal/ModalBody.tsx
  frontend/src/components/Room/Modal/ModalFooter.tsx
  frontend/src/components/Room/Modal/ModalHeader.tsx
  frontend/src/components/Room/Room.style.ts
  frontend/src/components/Room/Room.tsx
  frontend/src/components/Room/Room.types.ts
  frontend/src/components/Room/RoomImage.tsx
  frontend/src/components/Room/RoomOccupancy.tsx
  frontend/src/components/Room/RoomPriceInfo.tsx
  frontend/src/pages/Detail/Rooms.style.ts
  frontend/src/pages/Detail/Rooms.tsx
  frontend/src/pages/Reservation/Reservation.tsx
  frontend/src/utils/requests.ts
Labels: bug, refactoring

#206 리뷰 컴포넌트 리팩토링
  frontend/src/components/Payment/Payment.type.ts
  frontend/src/components/Review/Content/Content.style.ts
  frontend/src/components/Review/Content/Content.type.ts
  frontend/src/components/Review/Content/ContentHeader.tsx
  frontend/src/components/Review/Content/ContentImoji.tsx
  frontend/src/components/Review/Content/ContentInfo.tsx
  frontend/src/components/Review/Content/ContentMain.tsx
  frontend/src/components/Review/Loader.tsx
  frontend/src/components/Review/Review.style.ts
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/Review.type.ts
  frontend/src/components/Review/ReviewTitle.tsx
  frontend/src/components/Review/Title/AverageScore.tsx
  frontend/src/components/Review/Title/NumberOfTitle.tsx
  frontend/src/components/Review/Title/Title.style.ts
  frontend/src/containers/Header/Header.tsx
  frontend/src/pages/Detail/Reviews.style.ts
  frontend/src/pages/Detail/TopReviews.tsx
  frontend/src/pages/Reservation/Reservation.tsx
  frontend/src/pages/Reviews/Reviews.tsx
  frontend/src/utils/requests.ts
  frontend/src/utils/reviews.ts
Labels: refactoring, type

#211 selectAuth 타입 추론
  frontend/src/app/app.tsx
  frontend/src/containers/Footer/Footer.tsx
  frontend/src/containers/Header/Header.tsx
  frontend/src/contexts/auth.ts
  frontend/src/contexts/rootReducer.ts
  frontend/src/contexts/state.type.ts
  frontend/src/contexts/store.ts
Labels: refactoring

#213 main page 컴포넌트에 swr 적용
  frontend/package.json
  frontend/src/app/app.tsx
  frontend/src/components/Index/CurrentGoods/CurrentGoods.tsx
  frontend/src/components/Index/LocalGoods/LocalGoods.tsx
  frontend/src/utils/requests.ts
  frontend/vite.config.ts
Labels: refactoring

#215 useReducer와 React.memo, useCallback을 사용한 컴포넌트 정리
  frontend/src/components/Payment/Agreement.tsx
  frontend/src/components/Payment/Payment.type.ts
  frontend/src/components/Payment/PaymentForm.tsx
  frontend/src/components/Payment/UserInfo.tsx
  frontend/src/components/Payment/Visiting.tsx
  frontend/src/components/Review/Content/ContentMain.tsx
  frontend/src/components/Room/Room.types.ts
  frontend/src/pages/Reservation/Reducer.ts
  frontend/src/pages/Reservation/Reservation.tsx
  frontend/src/pages/Reservation/Reservation.type.ts
Labels: refactoring, type

#217 객실 및 리뷰 컴포넌트 리팩토링
  frontend/src/components/CheckInOut/Calendar.tsx
  frontend/src/components/CheckInOut/CheckInOut.style.ts
  frontend/src/components/CheckInOut/CheckInOut.tsx
  frontend/src/components/CheckInOut/Date.type.ts
  frontend/src/components/Review/Content/ContentHeader.tsx
  frontend/src/components/Review/Content/ContentImoji.tsx
  frontend/src/components/Review/Content/ContentInfo.tsx
  frontend/src/components/Review/Content/ContentMain.tsx
  frontend/src/components/Review/Review.tsx
  frontend/src/components/Review/ReviewList.tsx
  frontend/src/components/Review/ReviewTitle.tsx
  frontend/src/components/Review/Title/AverageScore.tsx
  frontend/src/components/Review/Title/NumberOfTitle.tsx
  frontend/src/components/Review/TopBtn.tsx
  frontend/src/components/Room/Room.tsx
  frontend/src/components/Room/Selector/SelectBar.tsx
  frontend/src/components/Room/Selector/Selector.style.ts
  frontend/src/components/Room/Selector/Seletor.type.ts
  frontend/src/pages/Cart/Cart.style.ts
  frontend/src/pages/Cart/Cart.tsx
  frontend/src/pages/Detail/Rooms.style.ts
  frontend/src/pages/Detail/Rooms.tsx
  frontend/src/pages/Detail/TopReviews.tsx
  frontend/src/pages/Reviews/Reviews.tsx
Labels: style, refactoring, type

#220 객실 및 리뷰 SWR 적용
  frontend/src/components/Review/ReviewList.tsx
  frontend/src/components/Review/ReviewTitle.tsx
  frontend/src/pages/Detail/Rooms.tsx
  frontend/src/pages/Detail/TopReviews.tsx
Labels: feat, refactoring
