Repository thenolja/desktop, pull requests merged in 2022-03, with the labels that each got.

#40 #12 마이페이지 내 회원 정보 구현
  src/assets/hotels/photo1.webp
  src/assets/hotels/photo2.webp
  src/assets/hotels/photo3.webp
  src/assets/hotels/photo4.webp
  src/assets/hotels/photo5.webp
  src/assets/reviews/photo.webp
  src/components/Reservation/Reservation.style.ts
  src/components/Reservation/Reservation.tsx
  src/components/UserInfo/Profile.style.ts
  src/components/UserInfo/Profile.tsx
  src/components/UserInfo/UserInfo.tsx
  src/components/UserInfo/UserInfoForm.tsx
  src/data/hotels.json
  src/data/payment.json
  src/data/reservations.json
  src/data/reviews.json
  src/data/users.json
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/ProtectedRouter/ProtectedRouter.tsx
  src/pages/ProtectedRouter/PrtotectedRouter.ts
Labels: style, feat

#68 #18 Index 페이지에 DatePicker추가
  frontend/package.json
  frontend/src/components/Index/SearchForm/Input/DateInput.tsx
  frontend/src/components/Index/SearchForm/Input/EndDatPicker.tsx
  frontend/src/components/Index/SearchForm/Input/StartDatePicker.tsx
  frontend/src/components/Index/SearchForm/SearchForm.tsx
Labels: feat

#70 #67 캐러셀 스타일
  frontend/src/assets/star.png
  frontend/src/components/Carousels/Carousel.style.ts
  frontend/src/components/Carousels/CarouselLi/CarouselLi.style.ts
  frontend/src/components/Carousels/CarouselLi/CarouselLi.tsx
  frontend/src/components/Index/CurrentGoods/CurrentGoods.style.ts
  frontend/src/components/Index/CurrentGoods/CurrentGoods.tsx
  frontend/src/components/Index/LocalGoods/LocalGoods.tsx
  frontend/src/components/Index/LocalGoods/LocalGoods.type.ts
  frontend/src/components/Index/LocalGoods/localGoods.style.ts
  frontend/src/components/Index/SearchForm/Input/EndDatPicker.tsx
  frontend/src/components/Index/SearchForm/Input/StartDatePicker.tsx
Labels: style

#78 #76 호텔 찾기 API 추가
  frontend/src/components/Index/SearchForm/Input/PersoInput.tsx
  frontend/src/components/Index/SearchForm/Input/QueryInput.stype.ts
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/utils/requests.ts
Labels: feat

#77 #72 Redux-Persist 설치 및 root reducer에 적용
  frontend/package.json
  frontend/src/app/app.tsx
  frontend/src/components/Reservation/DatePicker.tsx
  frontend/src/components/Reservation/PostingReview.tsx
  frontend/src/components/UserInfo/Profile.tsx
  frontend/src/components/UserInfo/UserInfo.tsx
  frontend/src/components/UserInfo/UserInfoForm.tsx
  frontend/src/contexts/rootReducer.ts
  frontend/src/contexts/store.ts
  frontend/src/index.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/ProtectedRouter/ProtectedRouter.tsx
Labels: bug, auth

#86 #83 Index 폴더 이동
  frontend/src/app/app.tsx
  frontend/src/components/Index/Index.tsx
  frontend/src/pages/Index/Index.tsx
  frontend/src/pages/Search/Search.style.ts
  frontend/src/pages/Search/Search.tsx
  frontend/src/pages/Search/Search.type.ts
Labels: refactoring

#91 Fix: Auth 정보가 제대로 갱신되지 않는 문제 해결
  backend/data/users.json
  backend/server.js
  frontend/src/containers/Header/Header.tsx
  frontend/src/contexts/auth.ts
  frontend/src/utils/users.ts
Labels: bug, auth

#96 #67 Link 태그 추가
  frontend/src/components/Carousels/CarouselLi/CarouselLi.tsx
  frontend/src/components/Index/SearchForm/Input/EndDatPicker.tsx
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/pages/Search/Search.tsx
  frontend/src/pages/Search/SearchLi.tsx
  frontend/src/pages/Search/SearchList/SearchLi.style.ts
  frontend/src/pages/Search/SearchList/SearchLi.tsx
  frontend/src/utils/requests.ts
Labels: feat

#102 #98 검색 기능 수정
  frontend/src/components/Index/SearchForm/Input/InputDiv.style.ts
  frontend/src/components/Index/SearchForm/Input/PersoInput.tsx
  frontend/src/components/Index/SearchForm/Input/QueryInput.stype.ts
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/components/Index/SearchForm/Input/QueryList.type.ts
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/pages/Search/Search.tsx
  frontend/src/utils/requests.ts
Labels: feat

#104 #98 검색 기능 수정 추가
  frontend/src/components/Index/SearchForm/Input/QueryInput.stype.ts
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/pages/Search/Search.tsx
Labels: feat

#107 마이페이지 내 유저 정보 및 예약 목록 컴포넌트
  backend/data/hotels.json
  backend/data/reservations.json
  backend/data/reviews.json
  backend/data/users.json
  backend/server.js
  frontend/src/components/Reservation/Reservation.tsx
  frontend/src/components/UserInfo/UserInfo.tsx
  frontend/src/components/UserInfo/UserInfoForm.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/utils/reservations.ts
  frontend/src/utils/users.ts
Labels: auth, feat

#108 #80 검색 input 영역 수정
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/pages/Search/Search.tsx
Labels: bug

#115 Fix: #113 헤더 로그인 상태 반영 에러
  backend/server.js
  frontend/src/containers/Header/Header.tsx
  frontend/src/utils/users.ts
Labels: bug, auth

#121 #114 검색어 미입력시 검색 이벤트 비활성화
  frontend/package.json
  frontend/src/components/Index/SearchForm/Input/InputDiv.style.ts
  frontend/src/components/Index/SearchForm/Input/PersoInput.tsx
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/components/Index/SearchForm/Input/StyledDiv.type.ts
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/pages/Search/Search.style.ts
Labels: feat

#123 마이페이지 리뷰 기능
  backend/data/reservations.json
  backend/data/reviews.json
  backend/server.js
  frontend/src/components/Reservation/PostingReview.style.ts
  frontend/src/components/Reservation/PostingReview.tsx
  frontend/src/components/Reservation/Reservation.tsx
  frontend/src/utils/reviews.ts
Labels: style, feat

#130 Feat: update my review
  frontend/src/components/Reservation/PostingReview.tsx
  frontend/src/components/Reservation/Reservation.tsx
  frontend/src/components/UserInfo/UserInfoForm.tsx
Labels: bug, feat

#134 #128 추천 검색어 관련 오류 수정
  frontend/src/components/Index/CurrentGoods/CurrentGoods.tsx
  frontend/src/components/Index/SearchForm/Input/QueryInput.stype.ts
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/components/Room/Room.tsx
  frontend/src/components/SearchList/SearchLi.style.ts
  frontend/src/components/SearchList/SearchLi.tsx
  frontend/src/components/map/map.tsx
  frontend/src/containers/Header/Header.tsx
  frontend/src/pages/Index/Index.tsx
  frontend/src/pages/Search/Search.tsx
  frontend/src/utils/dateToISOString.ts
  frontend/src/utils/requests.ts
  package-lock.json
Labels: bug

#144 #140 코드 분할 적용
  frontend/package.json
  frontend/src/app/app.tsx
  frontend/src/components/HotelImage/HotelImage.tsx
  frontend/src/components/Index/CurrentGoods/CurrentGoods.tsx
  frontend/src/components/Review/ReviewList.tsx
  frontend/src/components/Room/DetailRoomInfo.tsx
  frontend/src/components/Room/Room.tsx
  frontend/src/components/SearchList/SearchLi.tsx
  frontend/src/pages/Reviews/Reviews.tsx
  frontend/src/pages/Search/Search.tsx
  frontend/src/utils/requests.ts
  frontend/vite.config.ts
Labels: feat

#147 Feat: 리뷰 작성시 기존 리뷰 별점 반영 #142
  backend/data/reservations.json
  frontend/src/components/Reservation/Date.ts
  frontend/src/components/Reservation/DatePicker.tsx
  frontend/src/components/Reservation/PostingReview.tsx
  frontend/src/components/Reservation/Reservation.tsx
  frontend/src/components/UserInfo/User.ts
  frontend/src/components/UserInfo/User.type.ts
  frontend/src/components/map/map.tsx
  frontend/src/pages/Detail/HotelIntro.tsx
Labels: feat, refactoring

#149 fix : import img for vite bundler's build issus
  frontend/src/components/Carousels/CarouselLi/CarouselLi.tsx
  frontend/src/components/Index/Notice/Notice.tsx
  frontend/src/components/Index/SearchForm/Input/EndDatPicker.tsx
  frontend/src/components/Index/SearchForm/Input/PersoInput.tsx
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/components/Index/SearchForm/Input/StartDatePicker.tsx
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/pages/Index/Index.tsx
  frontend/src/pages/Search/Search.tsx
  frontend/vite.config.ts
Labels: bug

#158 #157 package.json 명령어 추가
  .github/ISSUE_TEMPLATE/-----.md
  .github/ISSUE_TEMPLATE/feature_request.md
  frontend/src/components/Carousels/CarouselLi/CarouselLi.tsx
  frontend/src/components/DetailNavbar/DetailNavbar.style.ts
  frontend/src/components/DetailNavbar/DetailNavbar.tsx
  frontend/src/components/Index/Index.tsx
  frontend/src/components/Index/Notice/Notice.tsx
  frontend/src/components/Index/SearchForm/Input/EndDatPicker.tsx
  frontend/src/components/Index/SearchForm/Input/PersoInput.tsx
  frontend/src/components/Index/SearchForm/Input/Person.type.ts
  frontend/src/components/Index/SearchForm/Input/QueryInput.tsx
  frontend/src/components/Index/SearchForm/Input/StartDatePicker.tsx
  frontend/src/components/Index/SearchForm/SearchForm.tsx
  frontend/src/components/Reservation/Date.ts
  frontend/src/components/Review/Loader.tsx
  frontend/src/components/UserInfo/User.ts
  frontend/src/pages/Detail/Reviews.style.ts
  frontend/src/pages/Detail/Reviews.tsx
  frontend/src/pages/ProtectedRouter/PrtotectedRouter.ts
  frontend/src/pages/Search/Search.tsx
  frontend/src/pages/Search/SearchList/SearchLi.style.ts
  frontend/src/pages/Search/SearchList/SearchLi.tsx
  frontend/vite.config.ts
  package.json
Labels: feat

#174 리뷰 추가시 Auth 정보 갱신
  frontend/src/components/Reservation/DatePicker.tsx
  frontend/src/components/Reservation/PostingReview.tsx
  frontend/src/components/Reservation/Reservation.tsx
  frontend/src/components/UserInfo/Profile.style.ts
  frontend/src/components/UserInfo/Profile.tsx
  frontend/src/components/UserInfo/User.ts
  frontend/src/components/UserInfo/User.type.ts
  frontend/src/components/UserInfo/UserInfo.tsx
  frontend/src/components/UserInfo/UserInfoForm.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/utils/reviews.ts
Labels: auth, refactoring

#173 결제 페이지 변경 사항
  backend/server.js
  frontend/src/components/Payment/PaymentForm.tsx
  frontend/src/components/detail/HotelDescription.tsx
  frontend/src/pages/Reservation/Reservation.tsx
  frontend/src/utils/reservations.ts
Labels: refactoring

#177 결제페이지 추가사항 및 리팩토링
  frontend/package.json
  frontend/src/components/Payment/Notice.tsx
  frontend/src/components/Payment/Payment.style.ts
  frontend/src/components/Payment/PaymentForm.tsx
  frontend/src/components/Payment/Policy.tsx
  frontend/src/components/Payment/PriceInfo.tsx
  frontend/src/components/Payment/SelectedRoom.tsx
  frontend/src/components/Room/DetailRoomInfo.tsx
  frontend/src/components/Room/Room.tsx
  frontend/src/pages/Reservation/Reservation.tsx
Labels: style, feat, refactoring

#181 main 화면 컴포넌트 최적화
  frontend/index.html
  frontend/src/components/Carousels/CarouselLi/CarouselLi.style.ts
  frontend/src/components/Index/CurrentGoods/CurrentGoods.style.ts
  frontend/src/components/Index/LocalGoods/localGoods.style.ts
  frontend/src/containers/Main/Main.style.ts
  frontend/vite.config.ts
Labels: refactoring

#183 payment refactoring & modify mockdata
  backend/data/reservations.json
  backend/data/reviews.json
  backend/server.js
  frontend/src/components/Payment/Agreement.tsx
  frontend/src/components/Payment/Payment.style.ts
  frontend/src/components/Payment/Payment.type.ts
  frontend/src/components/Payment/PaymentForm.tsx
  frontend/src/components/Payment/PriceInfo.tsx
  frontend/src/components/Payment/SelectedRoom.tsx
  frontend/src/components/Payment/UserInfo.tsx
  frontend/src/components/Payment/Visiting.tsx
  frontend/src/pages/Reservation/Reservation.style.ts
  frontend/src/pages/Reservation/Reservation.tsx
  frontend/src/utils/requests.ts
Labels: refactoring
